### ISSUE TITLE
too easy tp escape sl-patched

### ISSUE THREAD

**Issue by djpiper28** [tkw1536/sl-patched#1]
you can suspend the program then kill it. this is undesired behaviour.

**Comment by tkw1536** [comment]
I don't believe there is a way for programs themselves to intercept a suspension attempt. You'd need an external program (e.g. system-wide daemon) or similar monitoring attempts, and that is far beyond the scope of this project.

**Comment by tkw1536** [comment]
Oops, spoke too soon and didn't even see your PR.

**Comment by djpiper28** [comment]
> Oops, spoke too soon and didn't even see your PR.

kekw
